# Generated by Django 2.2 on 2020-04-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='button_class',
            field=models.CharField(choices=[('message', 'message'), ('none', 'none')], default='none', max_length=20),
        ),
    ]
