# Generated by Django 2.1.5 on 2020-02-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200201_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
