# Generated by Django 2.1.5 on 2020-03-12 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200309_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='core.UserProfessor')),
                ('manager', models.ManyToManyField(to='core.UserProfessor')),
                ('member', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usercandidate',
            name='professor',
        ),
        migrations.AddField(
            model_name='usercandidate',
            name='professor',
            field=models.ManyToManyField(to='core.UserProfessor'),
        ),
    ]
