# Generated by Django 2.1.5 on 2020-02-17 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200205_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_candidate',
            field=models.BooleanField(default=False, verbose_name='candidate status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_professor',
            field=models.BooleanField(default=False, verbose_name='professor status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usercandidate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofessor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL),
        ),
    ]
