# Generated by Django 2.2 on 2020-04-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200405_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='button_class',
            field=models.CharField(choices=[('message', 'message'), ('none', 'none')], default='none', max_length=20),
        ),
    ]
