# Generated by Django 2.1.5 on 2020-02-01 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200201_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='core.Folder'),
            preserve_default=False,
        ),
    ]
