# Generated by Django 2.1.5 on 2020-02-01 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_file_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='core.Folder'),
        ),
        migrations.AlterField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
