# Generated by Django 2.1.5 on 2020-03-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200314_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='manager',
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default='test', max_length=70),
            preserve_default=False,
        ),
    ]
