# Generated by Django 2.2 on 2020-04-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200407_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofessor',
            name='self_website',
            field=models.URLField(blank=True),
        ),
    ]
