# Generated by Django 2.2 on 2020-04-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofessor_self_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofessor',
            name='self_website',
        ),
        migrations.AddField(
            model_name='user',
            name='self_website',
            field=models.URLField(blank=True),
        ),
    ]
