# Generated by Django 2.1.5 on 2020-02-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200204_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofessor',
            name='website',
        ),
    ]
